GROUP=dev.avinya.ads
VERSION_NAME=1.1.0
POM_ARTIFACT_ID=admob-cmp-gradle-plugin
POM_NAME=AdMob CMP Gradle Plugin
POM_DESCRIPTION=Links Google Mobile Ads/UMP into Kotlin/Native test executables for admob-cmp consumers.
POM_URL=https://github.com/Meet-Miyani/Admob-CMP
POM_LICENSE_NAME=Apache License 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_INCEPTION_YEAR=2025
POM_DEVELOPER_ID=Meet-Miyani
POM_DEVELOPER_NAME=Meet Miyani
POM_SCM_URL=https://github.com/Meet-Miyani/Admob-CMP
POM_SCM_CONNECTION=scm:git:https://github.com/Meet-Miyani/Admob-CMP.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Meet-Miyani/Admob-CMP.git
mavenCentralPublishing=true
mavenCentralAutomaticPublishing=false
signAllPublications=true
